debug: false
uuid: 0d8be2bc-753b-4b66-9c35-dfedbfd53f0b
token_id: 8kP2ShfVI7t6ojsB
token: bqvt2ft7jcJt0sOifaMQmUA1y9EhFgYQsEkUTQE5VNvqYeqIQxwUe9OfCYuzDpEG
api:
  host: 0.0.0.0
  port: 443
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/us-node-1.kswarrior.qzz.io/fullchain.pem
    key: /etc/letsencrypt/live/us-node-1.kswarrior.qzz.io/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'https://panel.kswarrior.qzz.io'
